version: 2.1
jobs:
  build:
    working_directory: ~/test
    docker: 
      - image: circleci/node:10.14.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.4.1'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}    
      - run:
          name: npm-install-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}  
          paths:
            - ./node_modules
  test:
    working_directory: ~/test
    docker: 
      - image: circleci/node:10.14.2
    steps:
      - checkout     
      - run:
          name: test
          command: npm test          
  
workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
         requires:
           - build:
  